const additionalData = [
   "Tajlandia",
   "Stany Zjednoczone Ameryki",
   "Australia",
   "Hongkong",
   "Kanada",
   "Nowa Zelandia",
   "Singapur",
   "Unia Europejska",
   "Węgry",
   "Szwajcaria",
   "Wielka Brytania",
   "Ukraina",
   "Japonia",
   "Czechy",
   "Dania",
   "Islandia",
   "Norwegia",
   "Szwecja",
   "Chorwacja",
   "Rumunia",
   "Bułgaria",
   "Turcja",
   "Izrael",
   "Chile",
   "Filipiny",
   "Meksyk",
   "Republika Południowej Afryki",
   "Brazylia",
   "Malezja",
   "Rosja",
   "Indonezja",
   "Indie",
   "Korea Południowa",
   "Chiny",
   "Międzynarodowa jednostka walutowa",
];

export {additionalData};
